import styles from '../styles/Header.module.css';
import Head from 'next/head';
const Header = () => {
    return (
        <>
            <Head>
                <title>Evently</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <h1 className={styles.title}>Evently</h1>
            </div>
        </>
    );
}

export default Header